/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as AuthenticatedAdminProductSlugRouteImport } from './routes/_authenticated/admin.product.$slug'
import { Route as ApiAffiliateRedirectOfferIdRouteImport } from './routes/api/affiliate/redirect.$offerId'
import { Route as ApiPublicCronFeedsRouteImport } from './routes/api/public/cron/feeds'
import { Route as ApiPublicCronInboxRouteImport } from './routes/api/public/cron/inbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProductSlugRoute =
  AuthenticatedAdminProductSlugRouteImport.update({
    id: '/product/$slug',
    path: '/product/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAffiliateRedirectOfferIdRoute =
  ApiAffiliateRedirectOfferIdRouteImport.update({
    id: '/api/affiliate/redirect/$offerId',
    path: '/api/affiliate/redirect/$offerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFeedsRoute = ApiPublicCronFeedsRouteImport.update({
  id: '/api/public/cron/feeds',
  path: '/api/public/cron/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronInboxRoute = ApiPublicCronInboxRouteImport.update({
  id: '/api/public/cron/inbox',
  path: '/api/public/cron/inbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/compare': typeof CompareRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/product/$slug': typeof AuthenticatedAdminProductSlugRoute
  '/api/affiliate/redirect/$offerId': typeof ApiAffiliateRedirectOfferIdRoute
  '/api/public/cron/feeds': typeof ApiPublicCronFeedsRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/compare': typeof CompareRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/product/$slug': typeof AuthenticatedAdminProductSlugRoute
  '/api/affiliate/redirect/$offerId': typeof ApiAffiliateRedirectOfferIdRoute
  '/api/public/cron/feeds': typeof ApiPublicCronFeedsRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/compare': typeof CompareRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/products/$slug': typeof ProductsSlugRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/product/$slug': typeof AuthenticatedAdminProductSlugRoute
  '/api/affiliate/redirect/$offerId': typeof ApiAffiliateRedirectOfferIdRoute
  '/api/public/cron/feeds': typeof ApiPublicCronFeedsRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/basket'
    | '/compare'
    | '/admin'
    | '/products/$slug'
    | '/admin/import'
    | '/api/public/unsubscribe'
    | '/admin/'
    | '/admin/product/$slug'
    | '/api/affiliate/redirect/$offerId'
    | '/api/public/cron/feeds'
    | '/api/public/cron/inbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/basket'
    | '/compare'
    | '/products/$slug'
    | '/admin/import'
    | '/api/public/unsubscribe'
    | '/admin'
    | '/admin/product/$slug'
    | '/api/affiliate/redirect/$offerId'
    | '/api/public/cron/feeds'
    | '/api/public/cron/inbox'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/basket'
    | '/compare'
    | '/_authenticated/admin'
    | '/products/$slug'
    | '/_authenticated/admin/import'
    | '/api/public/unsubscribe'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/product/$slug'
    | '/api/affiliate/redirect/$offerId'
    | '/api/public/cron/feeds'
    | '/api/public/cron/inbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BasketRoute: typeof BasketRoute
  CompareRoute: typeof CompareRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiAffiliateRedirectOfferIdRoute: typeof ApiAffiliateRedirectOfferIdRoute
  ApiPublicCronFeedsRoute: typeof ApiPublicCronFeedsRoute
  ApiPublicCronInboxRoute: typeof ApiPublicCronInboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/product/$slug': {
      id: '/_authenticated/admin/product/$slug'
      path: '/product/$slug'
      fullPath: '/admin/product/$slug'
      preLoaderRoute: typeof AuthenticatedAdminProductSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/affiliate/redirect/$offerId': {
      id: '/api/affiliate/redirect/$offerId'
      path: '/api/affiliate/redirect/$offerId'
      fullPath: '/api/affiliate/redirect/$offerId'
      preLoaderRoute: typeof ApiAffiliateRedirectOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/feeds': {
      id: '/api/public/cron/feeds'
      path: '/api/public/cron/feeds'
      fullPath: '/api/public/cron/feeds'
      preLoaderRoute: typeof ApiPublicCronFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/inbox': {
      id: '/api/public/cron/inbox'
      path: '/api/public/cron/inbox'
      fullPath: '/api/public/cron/inbox'
      preLoaderRoute: typeof ApiPublicCronInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductSlugRoute: typeof AuthenticatedAdminProductSlugRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProductSlugRoute: AuthenticatedAdminProductSlugRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BasketRoute: BasketRoute,
  CompareRoute: CompareRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiAffiliateRedirectOfferIdRoute: ApiAffiliateRedirectOfferIdRoute,
  ApiPublicCronFeedsRoute: ApiPublicCronFeedsRoute,
  ApiPublicCronInboxRoute: ApiPublicCronInboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
