/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CompareIndexRouteImport } from './routes/compare.index'
import { Route as CompareCreatineMonohydrateRouteImport } from './routes/compare.creatine-monohydrate'
import { Route as CompareMagnesiumGlycinateMalateRouteImport } from './routes/compare.magnesium-glycinate-malate'
import { Route as CompareOmega3FishOilRouteImport } from './routes/compare.omega-3-fish-oil'
import { Route as CompareVitaminD3K2RouteImport } from './routes/compare.vitamin-d3-k2'
import { Route as CompareWheyProteinIsolateRouteImport } from './routes/compare.whey-protein-isolate'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin.campaigns'
import { Route as AuthenticatedAdminFeedsRouteImport } from './routes/_authenticated/admin.feeds'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated/admin.people'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as ApiAffiliateCartRouteImport } from './routes/api/affiliate/cart'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as AuthenticatedAdminProductSlugRouteImport } from './routes/_authenticated/admin.product.$slug'
import { Route as ApiAffiliateRedirectOfferIdRouteImport } from './routes/api/affiliate/redirect.$offerId'
import { Route as ApiPublicCronFeedsRouteImport } from './routes/api/public/cron/feeds'
import { Route as ApiPublicCronInboxRouteImport } from './routes/api/public/cron/inbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRoute,
} as any)
const CompareCreatineMonohydrateRoute =
  CompareCreatineMonohydrateRouteImport.update({
    id: '/creatine-monohydrate',
    path: '/creatine-monohydrate',
    getParentRoute: () => CompareRoute,
  } as any)
const CompareMagnesiumGlycinateMalateRoute =
  CompareMagnesiumGlycinateMalateRouteImport.update({
    id: '/magnesium-glycinate-malate',
    path: '/magnesium-glycinate-malate',
    getParentRoute: () => CompareRoute,
  } as any)
const CompareOmega3FishOilRoute = CompareOmega3FishOilRouteImport.update({
  id: '/omega-3-fish-oil',
  path: '/omega-3-fish-oil',
  getParentRoute: () => CompareRoute,
} as any)
const CompareVitaminD3K2Route = CompareVitaminD3K2RouteImport.update({
  id: '/vitamin-d3-k2',
  path: '/vitamin-d3-k2',
  getParentRoute: () => CompareRoute,
} as any)
const CompareWheyProteinIsolateRoute =
  CompareWheyProteinIsolateRouteImport.update({
    id: '/whey-protein-isolate',
    path: '/whey-protein-isolate',
    getParentRoute: () => CompareRoute,
  } as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeedsRoute = AuthenticatedAdminFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAffiliateCartRoute = ApiAffiliateCartRouteImport.update({
  id: '/api/affiliate/cart',
  path: '/api/affiliate/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminProductSlugRoute =
  AuthenticatedAdminProductSlugRouteImport.update({
    id: '/product/$slug',
    path: '/product/$slug',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiAffiliateRedirectOfferIdRoute =
  ApiAffiliateRedirectOfferIdRouteImport.update({
    id: '/api/affiliate/redirect/$offerId',
    path: '/api/affiliate/redirect/$offerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFeedsRoute = ApiPublicCronFeedsRouteImport.update({
  id: '/api/public/cron/feeds',
  path: '/api/public/cron/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronInboxRoute = ApiPublicCronInboxRouteImport.update({
  id: '/api/public/cron/inbox',
  path: '/api/public/cron/inbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/compare/creatine-monohydrate': typeof CompareCreatineMonohydrateRoute
  '/compare/magnesium-glycinate-malate': typeof CompareMagnesiumGlycinateMalateRoute
  '/compare/omega-3-fish-oil': typeof CompareOmega3FishOilRoute
  '/compare/vitamin-d3-k2': typeof CompareVitaminD3K2Route
  '/compare/whey-protein-isolate': typeof CompareWheyProteinIsolateRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/compare/': typeof CompareIndexRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/feeds': typeof AuthenticatedAdminFeedsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/affiliate/cart': typeof ApiAffiliateCartRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/product/$slug': typeof AuthenticatedAdminProductSlugRoute
  '/api/affiliate/redirect/$offerId': typeof ApiAffiliateRedirectOfferIdRoute
  '/api/public/cron/feeds': typeof ApiPublicCronFeedsRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/compare/creatine-monohydrate': typeof CompareCreatineMonohydrateRoute
  '/compare/magnesium-glycinate-malate': typeof CompareMagnesiumGlycinateMalateRoute
  '/compare/omega-3-fish-oil': typeof CompareOmega3FishOilRoute
  '/compare/vitamin-d3-k2': typeof CompareVitaminD3K2Route
  '/compare/whey-protein-isolate': typeof CompareWheyProteinIsolateRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/compare': typeof CompareIndexRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/feeds': typeof AuthenticatedAdminFeedsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/affiliate/cart': typeof ApiAffiliateCartRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/product/$slug': typeof AuthenticatedAdminProductSlugRoute
  '/api/affiliate/redirect/$offerId': typeof ApiAffiliateRedirectOfferIdRoute
  '/api/public/cron/feeds': typeof ApiPublicCronFeedsRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/basket': typeof BasketRoute
  '/compare': typeof CompareRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/compare/creatine-monohydrate': typeof CompareCreatineMonohydrateRoute
  '/compare/magnesium-glycinate-malate': typeof CompareMagnesiumGlycinateMalateRoute
  '/compare/omega-3-fish-oil': typeof CompareOmega3FishOilRoute
  '/compare/vitamin-d3-k2': typeof CompareVitaminD3K2Route
  '/compare/whey-protein-isolate': typeof CompareWheyProteinIsolateRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/compare/': typeof CompareIndexRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/feeds': typeof AuthenticatedAdminFeedsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/api/affiliate/cart': typeof ApiAffiliateCartRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/product/$slug': typeof AuthenticatedAdminProductSlugRoute
  '/api/affiliate/redirect/$offerId': typeof ApiAffiliateRedirectOfferIdRoute
  '/api/public/cron/feeds': typeof ApiPublicCronFeedsRoute
  '/api/public/cron/inbox': typeof ApiPublicCronInboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/auth'
    | '/basket'
    | '/compare'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/compare/creatine-monohydrate'
    | '/compare/magnesium-glycinate-malate'
    | '/compare/omega-3-fish-oil'
    | '/compare/vitamin-d3-k2'
    | '/compare/whey-protein-isolate'
    | '/products/$slug'
    | '/compare/'
    | '/admin/campaigns'
    | '/admin/feeds'
    | '/admin/import'
    | '/admin/people'
    | '/admin/settings'
    | '/api/affiliate/cart'
    | '/api/public/unsubscribe'
    | '/admin/'
    | '/admin/product/$slug'
    | '/api/affiliate/redirect/$offerId'
    | '/api/public/cron/feeds'
    | '/api/public/cron/inbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/auth'
    | '/basket'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/compare/creatine-monohydrate'
    | '/compare/magnesium-glycinate-malate'
    | '/compare/omega-3-fish-oil'
    | '/compare/vitamin-d3-k2'
    | '/compare/whey-protein-isolate'
    | '/products/$slug'
    | '/compare'
    | '/admin/campaigns'
    | '/admin/feeds'
    | '/admin/import'
    | '/admin/people'
    | '/admin/settings'
    | '/api/affiliate/cart'
    | '/api/public/unsubscribe'
    | '/admin'
    | '/admin/product/$slug'
    | '/api/affiliate/redirect/$offerId'
    | '/api/public/cron/feeds'
    | '/api/public/cron/inbox'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/affiliate-disclosure'
    | '/auth'
    | '/basket'
    | '/compare'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/compare/creatine-monohydrate'
    | '/compare/magnesium-glycinate-malate'
    | '/compare/omega-3-fish-oil'
    | '/compare/vitamin-d3-k2'
    | '/compare/whey-protein-isolate'
    | '/products/$slug'
    | '/compare/'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/feeds'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/settings'
    | '/api/affiliate/cart'
    | '/api/public/unsubscribe'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/product/$slug'
    | '/api/affiliate/redirect/$offerId'
    | '/api/public/cron/feeds'
    | '/api/public/cron/inbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  AuthRoute: typeof AuthRoute
  BasketRoute: typeof BasketRoute
  CompareRoute: typeof CompareRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiAffiliateCartRoute: typeof ApiAffiliateCartRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiAffiliateRedirectOfferIdRoute: typeof ApiAffiliateRedirectOfferIdRoute
  ApiPublicCronFeedsRoute: typeof ApiPublicCronFeedsRoute
  ApiPublicCronInboxRoute: typeof ApiPublicCronInboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/creatine-monohydrate': {
      id: '/compare/creatine-monohydrate'
      path: '/creatine-monohydrate'
      fullPath: '/compare/creatine-monohydrate'
      preLoaderRoute: typeof CompareCreatineMonohydrateRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/magnesium-glycinate-malate': {
      id: '/compare/magnesium-glycinate-malate'
      path: '/magnesium-glycinate-malate'
      fullPath: '/compare/magnesium-glycinate-malate'
      preLoaderRoute: typeof CompareMagnesiumGlycinateMalateRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/omega-3-fish-oil': {
      id: '/compare/omega-3-fish-oil'
      path: '/omega-3-fish-oil'
      fullPath: '/compare/omega-3-fish-oil'
      preLoaderRoute: typeof CompareOmega3FishOilRouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/vitamin-d3-k2': {
      id: '/compare/vitamin-d3-k2'
      path: '/vitamin-d3-k2'
      fullPath: '/compare/vitamin-d3-k2'
      preLoaderRoute: typeof CompareVitaminD3K2RouteImport
      parentRoute: typeof CompareRoute
    }
    '/compare/whey-protein-isolate': {
      id: '/compare/whey-protein-isolate'
      path: '/whey-protein-isolate'
      fullPath: '/compare/whey-protein-isolate'
      preLoaderRoute: typeof CompareWheyProteinIsolateRouteImport
      parentRoute: typeof CompareRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feeds': {
      id: '/_authenticated/admin/feeds'
      path: '/feeds'
      fullPath: '/admin/feeds'
      preLoaderRoute: typeof AuthenticatedAdminFeedsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/affiliate/cart': {
      id: '/api/affiliate/cart'
      path: '/api/affiliate/cart'
      fullPath: '/api/affiliate/cart'
      preLoaderRoute: typeof ApiAffiliateCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/product/$slug': {
      id: '/_authenticated/admin/product/$slug'
      path: '/product/$slug'
      fullPath: '/admin/product/$slug'
      preLoaderRoute: typeof AuthenticatedAdminProductSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/affiliate/redirect/$offerId': {
      id: '/api/affiliate/redirect/$offerId'
      path: '/api/affiliate/redirect/$offerId'
      fullPath: '/api/affiliate/redirect/$offerId'
      preLoaderRoute: typeof ApiAffiliateRedirectOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/feeds': {
      id: '/api/public/cron/feeds'
      path: '/api/public/cron/feeds'
      fullPath: '/api/public/cron/feeds'
      preLoaderRoute: typeof ApiPublicCronFeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/inbox': {
      id: '/api/public/cron/inbox'
      path: '/api/public/cron/inbox'
      fullPath: '/api/public/cron/inbox'
      preLoaderRoute: typeof ApiPublicCronInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminFeedsRoute: typeof AuthenticatedAdminFeedsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductSlugRoute: typeof AuthenticatedAdminProductSlugRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
  AuthenticatedAdminFeedsRoute: AuthenticatedAdminFeedsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminProductSlugRoute: AuthenticatedAdminProductSlugRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CompareRouteChildren {
  CompareCreatineMonohydrateRoute: typeof CompareCreatineMonohydrateRoute
  CompareMagnesiumGlycinateMalateRoute: typeof CompareMagnesiumGlycinateMalateRoute
  CompareOmega3FishOilRoute: typeof CompareOmega3FishOilRoute
  CompareVitaminD3K2Route: typeof CompareVitaminD3K2Route
  CompareWheyProteinIsolateRoute: typeof CompareWheyProteinIsolateRoute
  CompareIndexRoute: typeof CompareIndexRoute
}

const CompareRouteChildren: CompareRouteChildren = {
  CompareCreatineMonohydrateRoute: CompareCreatineMonohydrateRoute,
  CompareMagnesiumGlycinateMalateRoute: CompareMagnesiumGlycinateMalateRoute,
  CompareOmega3FishOilRoute: CompareOmega3FishOilRoute,
  CompareVitaminD3K2Route: CompareVitaminD3K2Route,
  CompareWheyProteinIsolateRoute: CompareWheyProteinIsolateRoute,
  CompareIndexRoute: CompareIndexRoute,
}

const CompareRouteWithChildren =
  CompareRoute._addFileChildren(CompareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  AuthRoute: AuthRoute,
  BasketRoute: BasketRoute,
  CompareRoute: CompareRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiAffiliateCartRoute: ApiAffiliateCartRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiAffiliateRedirectOfferIdRoute: ApiAffiliateRedirectOfferIdRoute,
  ApiPublicCronFeedsRoute: ApiPublicCronFeedsRoute,
  ApiPublicCronInboxRoute: ApiPublicCronInboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
